# .travis.yml based on
# https://github.com/DRMacIver/hypothesis/blob/master/.travis.yml
# Setting the language to C overrides our CC environment variable
# and disables ccache.
# Setting it to python overrides our TRAVIS_PYTHON_VERSION (which
# we're only using in hopes of being able to go *back* to using
# python: one day so making the migration simpler)
language: minimal
dist: xenial
group: travis_latest

env:
    global:
        - BUILD_RUNTIMES=$HOME/.runtimes
        - PYTHONHASHSEED=8675309
        - CC="ccache gcc"
        - CCACHE_NOCPP2=true
        - CCACHE_SLOPPINESS=file_macro,time_macros,include_file_ctime,include_file_mtime
        - CCACHE_NOHASHDIR=true
        - BUILD_LIBS=$HOME/.libs
        - CFLAGS="-g -pipe"
        - CPPFLAGS="-I$BUILD_LIBS/include"
        - LDFLAGS="-L$BUILD_LIBS/lib"
        - LD_LIBRARY_PATH="-L$BUILD_LIBS/lib"

    # Note that this list is again *manually* expanded
    # for the 'cache' stage. The benefit of doing this (instead of
    # only listing a single version here, or using a different 'language')
    # is that we get separate caches per version. This keeps them small,
    # and prevents stepping on each other when we change Python minor
    # versions.

    # We do it here, rather than with the python: keyword
    # because the way travis handles pypy is pretty messed up.

    # Recall that unless otherwise specified, jobs inherit
    # the first entry in this list.
    matrix:
      - TRAVIS_PYTHON_VERSION=2.7
      - TRAVIS_PYTHON_VERSION=3.5
      - TRAVIS_PYTHON_VERSION=3.6
      - TRAVIS_PYTHON_VERSION=3.7
      - TRAVIS_PYTHON_VERSION=pypy2.7
      - TRAVIS_PYTHON_VERSION=pypy3.6

matrix:
  fast_finish: true

stages:
  - build-gevent
  - test

jobs:
  include:
    - &build-gevent
      stage: build-gevent
      install:
        # Install the Python runtime
        - time ./scripts/install.sh $TRAVIS_PYTHON_VERSION
        # Install the C dependencies to a known location.
        # This is used to test "no embed" cases, but also primes the
        # CCache for when we do embed. We have to do this in each
        # part of the matrix expansion to get it cached.
        - pushd deps/libev && ./configure --prefix=$BUILD_LIBS && make install && popd
        - pushd deps/c-ares && ./configure --prefix=$BUILD_LIBS && make install && popd
        - pushd deps/libuv && ./autogen.sh && ./configure --disable-static --prefix=$BUILD_LIBS && make install && popd
        - ls -l $BUILD_LIBS
        # Install gevent, including building anything needed and
        # getting the deps. This will have to be repeated for the
        # subsequent stages, but much of it should be cached here.
        # XXX: This syntax isn't working for some reason, nothing happens.
        - *install-gevent
      script:
        - ccache -s
    - <<: *build-gevent
      env: TRAVIS_PYTHON_VERSION=3.5
    - <<: *build-gevent
      env: TRAVIS_PYTHON_VERSION=3.6
    - <<: *build-gevent
      env: TRAVIS_PYTHON_VERSION=3.7
    - <<: *build-gevent
      env: TRAVIS_PYTHON_VERSION=pypy2.7
    - <<: *build-gevent
      env: TRAVIS_PYTHON_VERSION=pypy3.6

    - stage: test
      script: make alltest cffibackendtest
      install:
        - >
          EMBED=0
          PATH=$BUILD_RUNTIMES/snakepit/$TRAVIS_PYTHON_VERSION.d/bin:$PATH
          python -m pip install --no-warn-script-location -r dev-requirements.txt

install:
  - ls -l $BUILD_RUNTIMES/snakepit/
  - echo $BUILD_RUNTIMES/snakepit/$TRAVIS_PYTHON_VERSION.d
  - ls -l $BUILD_RUNTIMES/snakepit/$TRAVIS_PYTHON_VERSION.d
  - &install-gevent >
      GEVENTSETUP_EV_VERIFY=3
      PATH=$BUILD_RUNTIMES/snakepit/$TRAVIS_PYTHON_VERSION.d/bin:$PATH
      python -m pip install --no-warn-script-location -r dev-requirements.txt
script:
    - time make test-$TRAVIS_PYTHON_VERSION


notifications:
  email: false


cache:
  pip: true
  directories:
    - $HOME/.venv
    - $HOME/.runtimes
    - $HOME/.wheelhouse
    - $HOME/.ccache
    - $HOME/.libs

before_cache:
    - rm -f $HOME/.cache/pip/log/debug.log
