# .travis.yml based on https://github.com/DRMacIver/hypothesis/blob/master/.travis.yml
language: python
dist: xenial
group: travis_latest
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - pypy
  - pypy3

env:
    global:
        - BUILD_RUNTIMES=$HOME/.runtimes
        - PYTHONHASHSEED=8675309
        - CC="ccache gcc"
        - CCACHE_NOCPP2=true
        - CCACHE_SLOPPINESS=file_macro,time_macros,include_file_ctime,include_file_mtime
        - CCACHE_NOHASHDIR=true
        - CFLAGS="-g -pipe"

matrix:
  fast_finish: true

jobs:
  include:
    - stage: cache
      script: ./scripts/install.sh $TRAVIS_PYTHON_VERSION
    - stage: test
      env: TASK=test-py27-noembed
      script: make $TASK
install:
  - ./scripts/install.sh $TRAVIS_PYTHON_VERSION

script:
    - make test-$TRAVIS_PYTHON_VERSION


notifications:
  email: false


cache:
  pip: true
  directories:
    - $HOME/.venv
    - $HOME/.runtimes
    - $HOME/.wheelhouse
    - $HOME/.ccache

before_cache:
    - rm -f $HOME/.cache/pip/log/debug.log
