# .travis.yml based on
# https://github.com/DRMacIver/hypothesis/blob/master/.travis.yml
# Setting the language to C overrides our CC environment variable
# and disables ccache.
language: python
dist: xenial
group: travis_latest

env:
    global:
        - BUILD_RUNTIMES=$HOME/.runtimes
        - PYTHONHASHSEED=8675309
        - CC="ccache gcc"
        - CCACHE_NOCPP2=true
        - CCACHE_SLOPPINESS=file_macro,time_macros,include_file_ctime,include_file_mtime
        - CCACHE_NOHASHDIR=true
        - CFLAGS="-g -pipe"

    # Note that this list is again *manually* expanded
    # for the 'cache' stage. The benefit of doing this (instead of
    # only listing a single version here, or using a different 'language')
    # is that we get separate caches per version. This keeps them small,
    # and prevents stepping on each other when we change Python minor
    # versions.

    # We do it here, rather than with the python: keyword
    # because the way travis handles pypy is pretty messed up.

    # Recall that unless otherwise specified, jobs inherit
    # the first entry in this list.
    matrix:
      - TRAVIS_PYTHON_VERSION=2.7
      - TRAVIS_PYTHON_VERSION=3.5
      - TRAVIS_PYTHON_VERSION=3.6
      - TRAVIS_PYTHON_VERSION=3.7
      - TRAVIS_PYTHON_VERSION=pypy2.7
      - TRAVIS_PYTHON_VERSION=pypy3.6

matrix:
  fast_finish: true

stages:
  - cache
  - test

jobs:
  include:
    - &cache-stage
      stage: cache
      script: ./scripts/install.sh $TRAVIS_PYTHON_VERSION
    - <<: *cache-stage
      env: TRAVIS_PYTHON_VERSION=3.5
    - <<: *cache-stage
      env: TRAVIS_PYTHON_VERSION=3.6
    - <<: *cache-stage
      env: TRAVIS_PYTHON_VERSION=3.7
    - <<: *cache-stage
      env: TRAVIS_PYTHON_VERSION=pypy2.7
    - <<: *cache-stage
      env: TRAVIS_PYTHON_VERSION=pypy3.6

    - stage: test
      env: TASK=test-py27-noembed
      script: make $TASK


script:
    - time make test-$TRAVIS_PYTHON_VERSION


notifications:
  email: false


cache:
  pip: true
  directories:
    - $HOME/.venv
    - $HOME/.runtimes
    - $HOME/.wheelhouse
    - $HOME/.ccache

before_cache:
    - rm -f $HOME/.cache/pip/log/debug.log
